chatapp/urls.py
from django.urls import path
from . import views

app_name = 'chatapp'

urlpatterns = [
    path('gledaj/', views.gledaj, name='chatapp-gledaj'),
    path('send/', views.send, name='chatapp-send'),
    path('getMessages/', views.getMessages, name='getMessages'),
]

formula_app/urls.py
from django.urls import path
from . import views

app_name = 'formula_app'

urlpatterns = [
    path('', views.home, name='app-odbrojuvanje'),
    path('novosti/', views.novosti, name='app-novosti'),
    path('novost?<novost_naslov>', views.otvorena_novost, name='app-otvorena-novost'),
    path('plasman/', views.plasman, name='app-plasman'),
    path('raspored/', views.raspored, name='app-raspored'),
    path('traka-info?<traka_id>', views.traka_info, name='app-traka-info'),
    # path('gledaj/', views.gledaj, name='app-gledaj'),
    # 
    path('manage/', views.manage, name='app-manage'),
    # 
    path("register/", views.register_request, name="app-register"),
    path("login/", views.login_request, name="app-login"),
    path("welcome", views.welcome, name="app-welcome"),
]

formula_eden/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('formula_app.urls', namespace='formula_app')),
    path('', include('chatapp.urls', namespace='chatapp')),
]

formula_app/models.py
from unittest.util import _MAX_LENGTH
from django.db import models
from django.utils import timezone
import datetime


class Tim(models.Model):
    ime = models.CharField(max_length=50)
    pozicija = models.IntegerField(default=0)
    poeni = models.IntegerField(default=0)

    def __str__(self):
        return f"{self.ime}"

    class Meta:
        verbose_name = "Тим"
        verbose_name_plural = "Тимови"


def get_placeholder_team():
    '''
    Za da moze da ima default vrednost Vozac.tim
    ne treba uopste da ima potreba od ovoa osven ako ne dodadat nov vozac mid-season
    '''
    return Tim.objects.get_or_create(ime="default")[0]


class Vozac(models.Model):
    ime = models.TextField()
    prezime = models.TextField()
    pozicija = models.IntegerField(default=0)
    poeni = models.IntegerField(default=0)
    tim = models.ForeignKey(Tim, on_delete=models.SET(get_placeholder_team), default=get_placeholder_team)
    drzava = models.TextField()
    slika = models.TextField(default="nema-slika")

    def __str__(self):
        return f"{self.ime} {self.prezime}"

    class Meta:
        verbose_name = "Возач"
        verbose_name_plural = "Возачи"
    

# =================================================================== #

class Sesija(models.Model):
    session_id = models.IntegerField(default=0)
    ime = models.TextField()
    trka_ime = models.TextField()
    datum = models.DateTimeField(default=timezone.now, blank=True, null=True)

    def __str__(self):
        return f"{self.session_id} {self.ime}"

    class Meta:
        verbose_name = "Сесија"
        verbose_name_plural = "Сесии"


class Trka(models.Model):
    race_id = models.IntegerField()
    status = models.TextField()
    ime = models.TextField()
    drzava = models.TextField()
    staza = models.TextField()
    pocetok = models.DateField(default=datetime.datetime.now().strftime('%Y-%m-%d'))
    kraj = models.DateField(default=datetime.datetime.now().strftime('%Y-%m-%d'))
    sesii = models.ManyToManyField(Sesija, through='TrkaSesija', through_fields=('trka', 'sesija'), blank=True)
    staza_slika = models.TextField(default="nema")
    pozadina_slika = models.TextField(default="nema")

    def __str__(self):
        return f"{self.ime}"

    def get_closest_race(self, target):
        return self.filter(dt__gt=target).order_by('kraj')
    
    class Meta:
        verbose_name = "Трка"
        verbose_name_plural = "Трки"



class TrkaSesija(models.Model):
    trka = models.ForeignKey(Trka, on_delete=models.CASCADE)
    sesija = models.ForeignKey(Sesija, on_delete=models.CASCADE)

    def __str__(self):
        return f"{self.trka}: {self.sesija}"
    
    class Meta:
        verbose_name = "Трка-Сесија"
        verbose_name_plural = "Трки-Сесии"

# =================================================================== #

class Vest(models.Model):
    naslov = models.CharField(max_length=500)
    privju = models.CharField(max_length=1000)
    url = models.CharField(max_length=500)
    slika = models.CharField(max_length=500)
    tekst = models.TextField()
    skrejp_datum = models.DateTimeField(default=timezone.now)
    source = models.CharField(max_length=30)

    def __str__(self) -> str:
        return self.naslov
    
    class Meta:
        verbose_name = "Вест"
        verbose_name_plural = "Вести"

formula_app/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.models import User


class NewUserForm(UserCreationForm):
	password1 = forms.CharField(widget=forms.PasswordInput(attrs={'class': 'form-control'}))
	password2 = forms.CharField(widget=forms.PasswordInput(attrs={'class': 'form-control'}))

	# def save(self, commit=True):
	# 	user = super(NewUserForm, self).save(commit=False)
	# 	user.email = self.cleaned_data['email']
	# 	if commit:
	# 		user.save()
	# 	return user

	class Meta:
		model = User
		fields=['username','password1','password2']
		widgets = {
			'username': forms.TextInput(attrs={'class':'form-control'}),
		}

formula_app/views.py
import datetime
from django.utils import timezone
import traceback
from django.views.decorators.http import require_http_methods
from django.shortcuts import render, redirect
from django.contrib.admin.views.decorators import staff_member_required
from django.contrib.auth.decorators import login_required
from django.contrib.auth import login, logout
from django.contrib import messages
from django.contrib.auth.forms import AuthenticationForm
from django.contrib.auth import login, authenticate
from django.contrib.auth.decorators import user_passes_test
from django.db.models import Q
from formula_app.scrapers.standings import get_driver_standings, get_constructor_standings, get_races
from formula_app.scrapers import telma, sportskimk, sporteden
from .models import Tim, Vest, Vozac, Trka
from formula_app.forms import NewUserForm


def get_sledna_trka_i_sesija() -> tuple:
    sledni_trki = Trka.objects.filter(status="Confirmed", kraj__gte=datetime.datetime.now()).order_by("kraj")
    # imase problem tuka zavrsat site sesii a stoe uste istata trka (oti cel den e datata na nea so ja dobiva od APIto) zatoa e vaka so sesii da proveruva u edno
    return (sledni_trki.first(), sesija) if (sesija := sledni_trki.first().sesii.all().filter(datum__gte=timezone.now()).order_by("datum").first()) else (sledni_trki[1], sledni_trki[1].sesii.all().filter(datum__gte=timezone.now()).order_by("datum").first())


def get_sledna_trka():
    return get_sledna_trka_i_sesija()[0]


@require_http_methods(["GET"])
def home(request):
    sledna_trka, sledna_sesija = get_sledna_trka_i_sesija()
    context = {
        "sledna_trka": sledna_trka,
        "sledna_sesija": sledna_sesija,
    }

    return render(request, 'formula_app/odbrojuvanje.html', context)


@require_http_methods(["GET"])
def novosti(request):
    # "-skrejp_datum" e rastecki a samo "skrejpy_datum" e opagjacki
    # ili obratno proveri koa ke scrape nes nova vest
    vesti = Vest.objects.all().order_by("-skrejp_datum")
    sledna_trka = get_sledna_trka()
    
    context = {
        "veesti": vesti,
        "sledna_trka": sledna_trka,
    }

    return render(request, 'formula_app/novosti.html', context)


@require_http_methods(["GET"])
def plasman(request):
    sledna_trka = get_sledna_trka()
    vozaci = Vozac.objects.all()
    timovi = Tim.objects.all().filter(~Q(ime="default"))

    context = {
        "vozaci": vozaci,
        "timovi": timovi,
        "sledna_trka": sledna_trka,
    }

    return render(request, 'formula_app/plasman.html', context)


@require_http_methods(["GET"])
def raspored(request):
    trki = Trka.objects.all()
    sledna_trka = get_sledna_trka()

    context = {
        "trki": trki,
        "sledna_trka": sledna_trka,
    }

    return render(request, 'formula_app/raspored.html', context)


@require_http_methods(["GET"])
def traka_info(request, traka_id): 
    selektirana_trka = Trka.objects.all().filter(race_id=traka_id).first()
    sledna_trka = get_sledna_trka()

    context = {
        "sledna_trka": sledna_trka,
        "traka": selektirana_trka,
    }

    return render(request, 'formula_app/traka-info.html', context)


@require_http_methods(["GET"])
def otvorena_novost(request, novost_naslov):
    sledna_trka = get_sledna_trka()
    selektirana_vest = Vest.objects.all().filter(naslov=novost_naslov).first()
    vesti = Vest.objects.all().order_by('-skrejp_datum')[:2]

    context = {
        "sledna_trka": sledna_trka,
        "novost": selektirana_vest,
        "vesti": vesti,
    }

    return render(request, 'formula_app/otvorena-vest.html', context)


@require_http_methods(["GET"])
@staff_member_required()
def manage(request):
    context = dict()
    if(request.GET.get('update_driver_standings')):
        try:
            status = get_driver_standings()
            context = {
                "status_message": status,
            }
        except Exception as e:
            tb = traceback.format_exc()
            context = {
                "status_message": tb,
            }
        
    if(request.GET.get('update_team_standings')):
        try:
            status = get_constructor_standings()
            context = {
                "status_message": status,
            }
        except Exception as e:
            tb = traceback.format_exc()
            context = {
                "status_message": tb,
            }

    if(request.GET.get('update_races')):
        try:
            status = get_races()
            context = {
                "status_message": status,
            }
        except Exception as e:
            tb = traceback.format_exc()
            context = {
                "status_message": tb,
            }

    if(request.GET.get('update_telma_vesti')):
        try:
            status = telma.scrape()
            context = {
                "status_message": status,
            }
        except Exception as e:
            tb = traceback.format_exc()
            context = {
                "status_message": tb,
            }

    if(request.GET.get('update_sportskimk_vesti')):
        try:
            status = sportskimk.scrape()
            context = {
                "status_message": status,
            }
        except Exception as e:
            tb = traceback.format_exc()
            context = {
                "status_message": tb,
            }

    if(request.GET.get('update_sporteden_vesti')):
        try:
            status = sporteden.scrape()
            context = {
                "status_message": status,
            }
        except Exception as e:
            tb = traceback.format_exc()
            context = {
                "status_message": tb,
            }
    sledna_trka = get_sledna_trka()
    context["sledna_trka"] = sledna_trka

    return render(request, 'formula_app/manage.html', context=context)


@require_http_methods(["GET", "POST"])
@user_passes_test(lambda u: not u.is_authenticated, login_url="formula_app:app-welcome")
def register_request(request):
    if request.method == "POST":
        form = NewUserForm(request.POST)
        if form.is_valid():
            user = form.save()
            login(request, user)
            messages.success(request, "Registration successful." )
            if "next" in request.POST:
                return redirect(request.POST.get("next"))
            return redirect("formula_app:app-welcome")
        messages.error(request, "Unsuccessful registration. Invalid information.")
    form = NewUserForm()

    sledna_trka = get_sledna_trka()
    context = {
        "form":form,
        "sledna_trka": sledna_trka,
    }

    return render (request=request, template_name="formula_app/register.html", context=context)


@require_http_methods(["GET", "POST"])
@user_passes_test(lambda u: not u.is_authenticated, login_url="formula_app:app-welcome")
def login_request(request):
    if request.method == "POST":
        form = AuthenticationForm(request, data=request.POST)
        if form.is_valid():
            username = form.cleaned_data.get('username')
            password = form.cleaned_data.get('password')
            user = authenticate(username=username, password=password)
            if user is not None:
                login(request, user)
                messages.info(request, f"You are now logged in as {username}.")
                if "next" in request.POST:
                    return redirect(request.POST.get("next"))
                return redirect("formula_app:app-welcome")
            else:
                messages.error(request,"Invalid username or password.")
        else:
            messages.error(request,"Invalid username or password.")
    form = AuthenticationForm()

    sledna_trka = get_sledna_trka()
    context = {
        "form":form,
        "sledna_trka": sledna_trka,
    }

    return render(request=request, template_name="formula_app/login.html", context=context)


@require_http_methods(["GET", "POST"])
# ili @login_required namesto ovoa dole?
@user_passes_test(lambda u: u.is_authenticated)
def welcome(request):
    sledna_trka = get_sledna_trka()
    context = {
        "sledna_trka": sledna_trka,
    }
    return render(request, 'formula_app/welcome.html', context=context)

formula_app/templates/formula_app/base.html
{% load static %}
<!DOCTYPE HTML>
<html>

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge"> 
    <!-- TODO toa %now U samo za debugging-->
    <!-- za da ne cuva css u cache vaka na sekoj reload go vcituva odnovo -->
    <link rel="stylesheet" type="text/css" href="{% static 'formula_app/css/base.css' %}?{% now 'U' %}">
    <link rel="stylesheet" type="text/css" href="{% static 'formula_app/css/side-nav.css' %}?{% now 'U' %}">
    <link rel="stylesheet" type="text/css" href="{% static 'formula_app/css/scrollbar.css' %}?{% now 'U' %}">
    <script src="{% static 'formula_app/js/sideNav.js' %}"></script>
    <script src="{% static 'formula_app/js/stickyNavbar.js' %}"></script>
    {% block links %}{% endblock %}
    <title>Формула 1</title>
</head>

<body>
    <div id="mySidenav" class="sidenav">
        <a href="javascript:void(0)" class="closebtn" onclick="closeNav()">&times;</a>
        <a href="{% url 'formula_app:app-odbrojuvanje' %}" class="nav-but">ОДБРОЈУВАЊЕ</a>
        <a href="{% url 'formula_app:app-novosti' %}" class="nav-but">НОВОСТИ</a>
        <a href="{% url 'formula_app:app-plasman' %}" class="nav-but">ПЛАСМАН</a>
        <a href="{% url 'formula_app:app-raspored' %}" class="nav-but">РАСПОРЕД</a>
        <a href="{% url 'chatapp:chatapp-gledaj' %}" class="nav-but">ПРЕНОС ВО ЖИВО</a>
    </div>

    <header id="header">
        <div class="menu-icon" onclick="openNav()">
            <div class="menu-bar"></div>
            <div class="menu-bar"></div>
            <div class="menu-bar"></div>
        </div>
        <!-- <div class="new-menu" onclick="openNav()">&#9776;</div> -->

        <h2 id="traka">Следна трка: {{ sledna_trka.ime }} </h2>
        <div class="menu-icon" style="display: none;" onclick="openNav()">
            <div class="menu-bar"></div>
            <div class="menu-bar"></div>
            <div class="menu-bar"></div>
        </div>
    </header>

    {% block content %}{% endblock %}

</body>

</html>

formula_app/templates/formula_app/manage.html
{% extends "formula_app/base.html" %}
{% load static %}

{% block links %}
<link rel="stylesheet" type="text/css" href="{% static 'formula_app/css/novosti.css' %}?{% now 'U' %}">
<link rel="stylesheet" type="text/css" href="{% static 'formula_app/css/manage.css' %}?{% now 'U' %}">
{% endblock links %}

{% block content %}
<div class="manage-container">
    <form action="#" method="get" class="btn-container">
        <input type="submit" class="update-btn" value="UPDATE DRIVER STANDINGS" name="update_driver_standings">
        <input type="submit" class="update-btn" value="UPDATE TEAM STANDINGS" name="update_team_standings">
        <input type="submit" class="update-btn" value="UPDATE RACES" name="update_races">
        <input type="submit" class="update-btn vesti-btn" value="UPDATE TELMA VESTI" name="update_telma_vesti">
        <input type="submit" class="update-btn vesti-btn" value="UPDATE SPORTSKIMK VESTI" name="update_sportskimk_vesti">
        <input type="submit" class="update-btn vesti-btn" value="UPDATE SPORTEDEN VESTI" name="update_sporteden_vesti">
    </form>
    <pre class="blackbox">
{{ status_message }}
    </pre>
</div>
{% endblock content %}

formula_app/templates/formula_app/novosti.html
{% extends "formula_app/base.html" %}
{% load static %}

{% block links %}
<link rel="stylesheet" type="text/css" href="{% static 'formula_app/css/novosti.css' %}?{% now 'U' %}">
{% endblock links %}

{% block content %}
<div class="vesti" id="vesti">
    {% for vest in veesti %}
        
    <a class="karticka" href="{% url 'formula_app:app-otvorena-novost' novost_naslov=vest.naslov %}">
        <img src="{{ vest.slika }}">
        <h2>{{ vest.naslov }}</h2>
        <p>{{ vest.privju }}</p>
    </a>
    {% endfor %} 

</div>
{%  endblock content %}

formula_app/templates/formula_app/odbrojuvanje.html
{% load static %}
{% load formatter %}
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="IE=7">
    <meta http-equiv="X-UA-Compatible" content="ie=edge"> <!-- toa %now U samo za debugging-->
    <link rel="stylesheet" type="text/css" href="{% static 'formula_app/css/base.css' %}?{% now 'U' %}">
    <link rel="stylesheet" type="text/css" href="{% static 'formula_app/css/odbrojuvanje.css' %}?{% now 'U' %}">
</head>

<body>
    <div class="countdown" id="countdown" data-value="{{ sledna_sesija.datum|date:'Y-m-d H:i:s' }}">
        <h1 id="cntd"></h1>
        <h4>денови часови минути секунди</h4>
        <br>
        <h3>{{ sledna_sesija.ime|prevedi }}</h3>
        <br>
        <h2 id="traka">{{ sledna_trka.drzava }} - {{ sledna_trka.staza }}</h2>
    </div>
    <a href="{% url 'formula_app:app-novosti' %}" class="strelka">
        <img src="https://popupfilmresidency.org/wp-content/uploads/2019/05/white-down-arrow-png-2.png">
    </a>

    <script src="{% static 'formula_app/js/countdown.js' %}"></script>

</body>

</html>

formula_app/templates/formula_app/otvorena-vest.html
{% extends "formula_app/base.html" %}
{% load static %}

{% block links %}
<link rel="stylesheet" type="text/css" href="{% static 'formula_app/css/novosti.css' %}?{% now 'U' %}">
<link rel="stylesheet" type="text/css" href="{% static 'formula_app/css/otvorena-vest.css' %}?{% now 'U' %}">
{% endblock links %}

{% block content %}
    <div class="container">
        <div class="otvorena-novost">
            <img src="{{ novost.slika }}">
    
            <h2>{{ novost.naslov }}</h2>
    
            <p>{{ novost.tekst }}</p>
        </div>
    
        <div class="stranicni-vesti">
            {% for vest in vesti %}
                <div class="karticka">
                    <img src="{{ vest.slika }}">
                    <h2>{{ vest.naslov }}</h2>
                    <p>{{ vest.privju }}</p>
                </div>
            {% endfor %}
        </div>
    </div>

    <style>
        @media all and (max-width: 800px){
    .container{
        display: flex;
        align-items: center;
        flex-flow: column nowrap;
        justify-content: center;
    }
    .stanicni-vesti{
        width: 10vw;
        background-color: green !important;
    }
    .karticka{
        background-color: blue;
        width: 5vw;
    }

}
    </style>

{%  endblock content %}

formula_app/templates/formula_app/plasman.html
{% extends "formula_app/base.html" %}
{% load static %}
{% load formatter %}

{% block links %}
<link rel="stylesheet" type="text/css" href="{% static 'formula_app/css/plasman.css' %}?{% now 'U' %}">
{% endblock links %}

{% block content %}

<div class="plasman-container">

    <h2 id="vozaci">Возачи</h2>
    <div class="plasman-vozaci">

        {% for vozac in vozaci %}

        <div id="vozaci" class="p-vozac">
            <h2>{{ vozac.pozicija }}</h2>
            <div class="drugio-font vozac-ime-blok boja-{{ vozac.tim.ime|zameni_prazno_mesto }}" >
                <div>
                    {{ vozac.ime }} <b>{{ vozac.prezime }}</b>
                </div>
                <div class="text-boja-{{ vozac.tim.ime.split|join:'-' }}">{{ vozac.tim.ime }}</div>
                
                <!-- TODO Ovoa treba so imgs so se u STATIC foldero ne od internet da gi dava -->
                <img class="zname" src="https://www.countries-ofthe-world.com/flags-normal/flag-of-{{ vozac.drzava|zameni_procent_dvaese|zameni_prazno_mesto }}.png">
                
                <!-- ^ ne rabote so static -->
                <!-- <img src="{% static 'formula_app/imgs/flags/{{ vozac.nationality }}.png' %}"  -->
                
            </div>
            <!-- TODO ne treba vaka racno path da e treba so %static% -->
            <div class="slika-vozac" id="nema-hover">
                <span class="poeni"><b>{{ vozac.poeni }}</b> pts</span>
            </div>

            <div class="slika-vozac" id="samo-hover" style='background-image: url("{% static vozac.slika %}")'>
                <span class="poeni"><b>{{ vozac.poeni }}</b> pts</span>
            </div>
        </div>

        {% endfor %}
    </div>
    <h2 id="timovi">Тимови</h2>
    <div id="timovi" class="plasman-vozaci">

        {% for tim in timovi %}

        <div class="p-vozac">
            <h2>{{ tim.pozicija }}</h2>
            <div class="drugio-font vozac-ime-blok boja-{{ tim.ime|zameni_prazno_mesto }}" >
                <div class="text-boja-{{ tim.ime.split|join:'-' }}">{{ tim.ime }}</div>
                
            </div>
            <!-- TODO ne treba vaka racno path da e treba so %static% -->
            <div class="slika-vozac" id="nema-hover">
                <span class="poeni"><b>{{ tim.poeni }}</b> pts</span>
            </div>

            <div class="slika-vozac" id="samo-hover" style='background-image: url("{% static vozac.slika %}")'>
                <span class="poeni"><b>{{ tim.poeni }}</b> pts</span>
            </div>
        </div>

        {% endfor %}
    </div>

</div>
{% endblock content %}

formula_app/templates/formula_app/traka-info.html
{% extends "formula_app/base.html" %}
{% load static %}

{% block links %}
<link rel="stylesheet" type="text/css" href="{% static 'formula_app/css/traka-info.css' %}?{% now 'U' %}">
{% endblock links %}

{% block content %}
<div class="content">
    <!-- TODO slika od stazata da pokazuva tuka (od tie novite PNG ako ne izgledat loso inc SVG)-->
    <!-- Ako se SVG oti ne gi ima site ke treba nesto za default da se pokazuva -->
    <!-- <img src="" alt=""> -->
    <div class="staza-info">
        <div class="inf" data-vreme="{{ traka.sesii.all.0.datum }}">
            <p style="font-weight:100; color:gray;">Вежбање 1: </p>
        </div>
        <div class="inf" data-vreme="{{ traka.sessions.1.date }}">
            <p style="font-weight:100; color:gray;">Вежбање 2: </p>
        </div>
        <div class="inf" data-vreme="{{ traka.sessions.2.date }}">
            <p style="font-weight:100; color:gray;">Вежбање 3: </p>
        </div>
        <div class="inf" data-vreme="{{ traka.sessions.3.date }}">
            <p style="font-weight:100; color:gray;">Квалификации: </p>
        </div>
        <div class="inf" data-vreme="{{ traka.sessions.7.date }}">
            <p style="font-weight:100; color:gray;">Трка: </p>
        </div>
    </div>
</div>

<script>
    // TODO
    // staj go u poseben JS file ovoa (ne zabravaj toa "static" ke treba da se linknuva)
    var options = { weekday: 'long', year: 'numeric', month: '2-digit', day: '2-digit', hour: "2-digit", minute: "2-digit" };
    document.querySelectorAll(".inf").forEach(element => {
        var vreme = new Date(element.dataset.vreme).toLocaleDateString("en-UK", options).replace("/", ".").replace("/", ".");
        var data = vreme.split(",");
        var den = data[0];
        data.shift()

        switch(den){
            case "Monday":
                den = "Понеделник";
                break;
            case "Tuesday":
                den = "Вторник";
                break;
            case "Wednesday":
                den = "Среда";
                break;
            case "Thursday":
                den = "Четвтрок";
                break;
            case "Friday":
                den = "Петок";
                break;
            case "Saturday":
                den = "Сабота";
                break;
            default:
                den = "Недела";
                break;
        }
        
        console.log()

        element.innerHTML += den + data + "ч";
    });
</script>
{% endblock content %}

formula_app/templates/formula_app/welcome.html
{% extends "formula_app/base.html" %}
{% load static %}


{% block content %}
<h1>Authentication successful</h1>
<h2>Welcome</h2>
{% endblock content %}