chatapp/urls.py
from django.urls import path
from . import views

app_name = 'chatapp'

urlpatterns = [
    path('gledaj/', views.gledaj, name='chatapp-gledaj'),
    path('send/', views.send, name='chatapp-send'),
    path('getMessages/', views.getMessages, name='getMessages'),
]

formula_app/urls.py
from django.urls import path
from . import views

app_name = 'formula_app'

urlpatterns = [
    path('', views.home, name='app-odbrojuvanje'),
    path('novosti/', views.novosti, name='app-novosti'),
    path('novost?<novost_naslov>', views.otvorena_novost, name='app-otvorena-novost'),
    path('plasman/', views.plasman, name='app-plasman'),
    path('raspored/', views.raspored, name='app-raspored'),
    path('traka-info?<traka_id>', views.traka_info, name='app-traka-info'),
    # path('gledaj/', views.gledaj, name='app-gledaj'),
    # 
    path('manage/', views.manage, name='app-manage'),
    # 
    path("register/", views.register_request, name="app-register"),
    path("login/", views.login_request, name="app-login"),
    path("welcome", views.welcome, name="app-welcome"),
]

formula_eden/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('formula_app.urls', namespace='formula_app')),
    path('', include('chatapp.urls', namespace='chatapp')),
]

formula_app/models.py
from unittest.util import _MAX_LENGTH
from django.db import models
from django.utils import timezone
import datetime


class Tim(models.Model):
    ime = models.CharField(max_length=50)
    pozicija = models.IntegerField(default=0)
    poeni = models.IntegerField(default=0)

    def __str__(self):
        return f"{self.ime}"

    class Meta:
        verbose_name = "Тим"
        verbose_name_plural = "Тимови"


def get_placeholder_team():
    '''
    Za da moze da ima default vrednost Vozac.tim
    ne treba uopste da ima potreba od ovoa osven ako ne dodadat nov vozac mid-season
    '''
    return Tim.objects.get_or_create(ime="default")[0]


class Vozac(models.Model):
    ime = models.TextField()
    prezime = models.TextField()
    pozicija = models.IntegerField(default=0)
    poeni = models.IntegerField(default=0)
    tim = models.ForeignKey(Tim, on_delete=models.SET(get_placeholder_team), default=get_placeholder_team)
    drzava = models.TextField()
    slika = models.TextField(default="nema-slika")

    def __str__(self):
        return f"{self.ime} {self.prezime}"

    class Meta:
        verbose_name = "Возач"
        verbose_name_plural = "Возачи"
    

# =================================================================== #

class Sesija(models.Model):
    session_id = models.IntegerField(default=0)
    ime = models.TextField()
    trka_ime = models.TextField()
    datum = models.DateTimeField(default=timezone.now, blank=True, null=True)

    def __str__(self):
        return f"{self.session_id} {self.ime}"

    class Meta:
        verbose_name = "Сесија"
        verbose_name_plural = "Сесии"


class Trka(models.Model):
    race_id = models.IntegerField()
    status = models.TextField()
    ime = models.TextField()
    drzava = models.TextField()
    staza = models.TextField()
    pocetok = models.DateField(default=datetime.datetime.now().strftime('%Y-%m-%d'))
    kraj = models.DateField(default=datetime.datetime.now().strftime('%Y-%m-%d'))
    sesii = models.ManyToManyField(Sesija, through='TrkaSesija', through_fields=('trka', 'sesija'), blank=True)
    staza_slika = models.TextField(default="nema")
    pozadina_slika = models.TextField(default="nema")

    def __str__(self):
        return f"{self.ime}"

    def get_closest_race(self, target):
        return self.filter(dt__gt=target).order_by('kraj')
    
    class Meta:
        verbose_name = "Трка"
        verbose_name_plural = "Трки"



class TrkaSesija(models.Model):
    trka = models.ForeignKey(Trka, on_delete=models.CASCADE)
    sesija = models.ForeignKey(Sesija, on_delete=models.CASCADE)

    def __str__(self):
        return f"{self.trka}: {self.sesija}"
    
    class Meta:
        verbose_name = "Трка-Сесија"
        verbose_name_plural = "Трки-Сесии"

# =================================================================== #

class Vest(models.Model):
    naslov = models.CharField(max_length=500)
    privju = models.CharField(max_length=1000)
    url = models.CharField(max_length=500)
    slika = models.CharField(max_length=500)
    tekst = models.TextField()
    skrejp_datum = models.DateTimeField(default=timezone.now)
    source = models.CharField(max_length=30)

    def __str__(self) -> str:
        return self.naslov
    
    class Meta:
        verbose_name = "Вест"
        verbose_name_plural = "Вести"

formula_app/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.models import User


class NewUserForm(UserCreationForm):
	password1 = forms.CharField(widget=forms.PasswordInput(attrs={'class': 'form-control'}))
	password2 = forms.CharField(widget=forms.PasswordInput(attrs={'class': 'form-control'}))

	# def save(self, commit=True):
	# 	user = super(NewUserForm, self).save(commit=False)
	# 	user.email = self.cleaned_data['email']
	# 	if commit:
	# 		user.save()
	# 	return user

	class Meta:
		model = User
		fields=['username','password1','password2']
		widgets = {
			'username': forms.TextInput(attrs={'class':'form-control'}),
		}

formula_app/views.py
import datetime
from django.utils import timezone
import traceback
from django.views.decorators.http import require_http_methods
from django.shortcuts import render, redirect
from django.contrib.admin.views.decorators import staff_member_required
from django.contrib.auth.decorators import login_required
from django.contrib.auth import login, logout
from django.contrib import messages
from django.contrib.auth.forms import AuthenticationForm
from django.contrib.auth import login, authenticate
from django.contrib.auth.decorators import user_passes_test
from django.db.models import Q
from formula_app.scrapers.standings import get_driver_standings, get_constructor_standings, get_races
from formula_app.scrapers import telma, sportskimk, sporteden
from .models import Tim, Vest, Vozac, Trka
from formula_app.forms import NewUserForm


def get_sledna_trka_i_sesija() -> tuple:
    sledni_trki = Trka.objects.filter(status="Confirmed", kraj__gte=datetime.datetime.now()).order_by("kraj")
    # imase problem tuka zavrsat site sesii a stoe uste istata trka (oti cel den e datata na nea so ja dobiva od APIto) zatoa e vaka so sesii da proveruva u edno
    return (sledni_trki.first(), sesija) if (sesija := sledni_trki.first().sesii.all().filter(datum__gte=timezone.now()).order_by("datum").first()) else (sledni_trki[1], sledni_trki[1].sesii.all().filter(datum__gte=timezone.now()).order_by("datum").first())


def get_sledna_trka():
    return get_sledna_trka_i_sesija()[0]


@require_http_methods(["GET"])
def home(request):
    sledna_trka, sledna_sesija = get_sledna_trka_i_sesija()
    context = {
        "sledna_trka": sledna_trka,
        "sledna_sesija": sledna_sesija,
    }

    return render(request, 'formula_app/odbrojuvanje.html', context)


@require_http_methods(["GET"])
def novosti(request):
    # "-skrejp_datum" e rastecki a samo "skrejpy_datum" e opagjacki
    # ili obratno proveri koa ke scrape nes nova vest
    vesti = Vest.objects.all().order_by("-skrejp_datum")
    sledna_trka = get_sledna_trka()
    
    context = {
        "veesti": vesti,
        "sledna_trka": sledna_trka,
    }

    return render(request, 'formula_app/novosti.html', context)


@require_http_methods(["GET"])
def plasman(request):
    sledna_trka = get_sledna_trka()
    vozaci = Vozac.objects.all()
    timovi = Tim.objects.all().filter(~Q(ime="default"))

    context = {
        "vozaci": vozaci,
        "timovi": timovi,
        "sledna_trka": sledna_trka,
    }

    return render(request, 'formula_app/plasman.html', context)


@require_http_methods(["GET"])
def raspored(request):
    trki = Trka.objects.all()
    sledna_trka = get_sledna_trka()

    context = {
        "trki": trki,
        "sledna_trka": sledna_trka,
    }

    return render(request, 'formula_app/raspored.html', context)


@require_http_methods(["GET"])
def traka_info(request, traka_id): 
    selektirana_trka = Trka.objects.all().filter(race_id=traka_id).first()
    sledna_trka = get_sledna_trka()

    context = {
        "sledna_trka": sledna_trka,
        "traka": selektirana_trka,
    }

    return render(request, 'formula_app/traka-info.html', context)


@require_http_methods(["GET"])
def otvorena_novost(request, novost_naslov):
    sledna_trka = get_sledna_trka()
    selektirana_vest = Vest.objects.all().filter(naslov=novost_naslov).first()
    vesti = Vest.objects.all().order_by('-skrejp_datum')[:2]

    context = {
        "sledna_trka": sledna_trka,
        "novost": selektirana_vest,
        "vesti": vesti,
    }

    return render(request, 'formula_app/otvorena-vest.html', context)


@require_http_methods(["GET"])
@staff_member_required()
def manage(request):
    context = dict()
    if(request.GET.get('update_driver_standings')):
        try:
            status = get_driver_standings()
            context = {
                "status_message": status,
            }
        except Exception as e:
            tb = traceback.format_exc()
            context = {
                "status_message": tb,
            }
        
    if(request.GET.get('update_team_standings')):
        try:
            status = get_constructor_standings()
            context = {
                "status_message": status,
            }
        except Exception as e:
            tb = traceback.format_exc()
            context = {
                "status_message": tb,
            }

    if(request.GET.get('update_races')):
        try:
            status = get_races()
            context = {
                "status_message": status,
            }
        except Exception as e:
            tb = traceback.format_exc()
            context = {
                "status_message": tb,
            }

    if(request.GET.get('update_telma_vesti')):
        try:
            status = telma.scrape()
            context = {
                "status_message": status,
            }
        except Exception as e:
            tb = traceback.format_exc()
            context = {
                "status_message": tb,
            }

    if(request.GET.get('update_sportskimk_vesti')):
        try:
            status = sportskimk.scrape()
            context = {
                "status_message": status,
            }
        except Exception as e:
            tb = traceback.format_exc()
            context = {
                "status_message": tb,
            }

    if(request.GET.get('update_sporteden_vesti')):
        try:
            status = sporteden.scrape()
            context = {
                "status_message": status,
            }
        except Exception as e:
            tb = traceback.format_exc()
            context = {
                "status_message": tb,
            }
    sledna_trka = get_sledna_trka()
    context["sledna_trka"] = sledna_trka

    return render(request, 'formula_app/manage.html', context=context)


@require_http_methods(["GET", "POST"])
@user_passes_test(lambda u: not u.is_authenticated, login_url="formula_app:app-welcome")
def register_request(request):
    if request.method == "POST":
        form = NewUserForm(request.POST)
        if form.is_valid():
            user = form.save()
            login(request, user)
            messages.success(request, "Registration successful." )
            if "next" in request.POST:
                return redirect(request.POST.get("next"))
            return redirect("formula_app:app-welcome")
        messages.error(request, "Unsuccessful registration. Invalid information.")
    form = NewUserForm()

    sledna_trka = get_sledna_trka()
    context = {
        "form":form,
        "sledna_trka": sledna_trka,
    }

    return render (request=request, template_name="formula_app/register.html", context=context)


@require_http_methods(["GET", "POST"])
@user_passes_test(lambda u: not u.is_authenticated, login_url="formula_app:app-welcome")
def login_request(request):
    if request.method == "POST":
        form = AuthenticationForm(request, data=request.POST)
        if form.is_valid():
            username = form.cleaned_data.get('username')
            password = form.cleaned_data.get('password')
            user = authenticate(username=username, password=password)
            if user is not None:
                login(request, user)
                messages.info(request, f"You are now logged in as {username}.")
                if "next" in request.POST:
                    return redirect(request.POST.get("next"))
                return redirect("formula_app:app-welcome")
            else:
                messages.error(request,"Invalid username or password.")
        else:
            messages.error(request,"Invalid username or password.")
    form = AuthenticationForm()

    sledna_trka = get_sledna_trka()
    context = {
        "form":form,
        "sledna_trka": sledna_trka,
    }

    return render(request=request, template_name="formula_app/login.html", context=context)


@require_http_methods(["GET", "POST"])
# ili @login_required namesto ovoa dole?
@user_passes_test(lambda u: u.is_authenticated)
def welcome(request):
    sledna_trka = get_sledna_trka()
    context = {
        "sledna_trka": sledna_trka,
    }
    return render(request, 'formula_app/welcome.html', context=context)

templates/formula_app/login.html
{% extends "base.html" %}
{% load static %}    

{% block links %}
	<link type="text/css" rel="stylesheet" href="{% static 'formula_app/bootstrap/css/materialize.min.css' %}"  media="screen,projection"/>
	<link type="text/css" rel="stylesheet" href="{% static 'formula_app/bootstrap/css/style.css' %}"  media="screen,projection"/>

	<script type="text/javascript" src="https://code.jquery.com/jquery-3.2.1.min.js"></script>
	<script type="text/javascript" src="{% static 'formula_app/bootstrap/js/materialize.min.js' %}"></script>

{% endblock links %}

{% block content %}      
<!--Login--> 
<div class="container">
	<h1>Login</h1>
	<form class="form-group" method="POST" >
		{% csrf_token %}
		<div class="row">
			<div class="input-field col s12">
				{{ form.username }}
				<label for="id_username" data-error="Username already taken">Username</label>
			</div>
		</div>
		<div class="row">
			<div class="input-field col s12">
				{{ form.password }}
				<label for="id_password">Password</label>
			</div>
		</div>
		<div class="row">
			<div class="col s12">
			<div class="right">
				<button class="btn blue waves-effect waves-light pull-s12">Login</button>
			</div>
			</div>
	</form>
	{% if request.GET.next %}
		<input type="hidden" name="next" value="{{ request.GET.next }}">
		<p class="text-center">Don't have an account? <a href="/register/?next={{ request.GET.next }}">Create an account</a>.</p>
	{% else %}
		<p class="text-center">Don't have an account? <a href="/register">Create an account</a>.</p>
	{% endif %}
</div>

{% endblock %}

templates/formula_app/manage.html
{% extends "base.html" %}
{% load static %}

{% block links %}
<link rel="stylesheet" type="text/css" href="{% static 'formula_app/css/novosti.css' %}">
<link rel="stylesheet" type="text/css" href="{% static 'formula_app/css/manage.css' %}">
{% endblock links %}

{% block content %}
<div class="manage-container">
    <form action="#" method="get" class="btn-container">
        <input type="submit" class="update-btn" value="UPDATE DRIVER STANDINGS" name="update_driver_standings">
        <input type="submit" class="update-btn" value="UPDATE TEAM STANDINGS" name="update_team_standings">
        <input type="submit" class="update-btn" value="UPDATE RACES" name="update_races">
        <input type="submit" class="update-btn vesti-btn" value="UPDATE TELMA VESTI" name="update_telma_vesti">
        <input type="submit" class="update-btn vesti-btn" value="UPDATE SPORTSKIMK VESTI" name="update_sportskimk_vesti">
        <input type="submit" class="update-btn vesti-btn" value="UPDATE SPORTEDEN VESTI" name="update_sporteden_vesti">
    </form>
    <pre class="blackbox">
{{ status_message }}
    </pre>
</div>
{% endblock content %}

templates/formula_app/novosti.html
{% extends "base.html" %}
{% load static %}

{% block links %}
<link rel="stylesheet" type="text/css" href="{% static 'formula_app/css/novosti.css' %}">
{% endblock links %}

{% block content %}
<div class="vesti" id="vesti">
    {% for vest in veesti %}

    <a class="karticka" href="{% url 'formula_app:app-otvorena-novost' novost_naslov=vest.naslov %}">
        <div class="slika-container">
            <img src="{{ vest.slika }}">
        </div>
        <h2>{{ vest.naslov }}</h2>
        <p>{{ vest.privju }}</p>
    </a>
    {% endfor %}

</div>
{% endblock content %}

templates/formula_app/odbrojuvanje.html
{% load static %}
{% load formatter %}
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="IE=7">
    <meta http-equiv="X-UA-Compatible" content="ie=edge"> <!-- toa %now U samo za debugging-->
    <link rel="stylesheet" type="text/css" href="{% static 'formula_app/css/base.css' %}">
    <link rel="stylesheet" type="text/css" href="{% static 'formula_app/css/odbrojuvanje.css' %}">
    <link rel="stylesheet" type="text/css" href="{% static 'formula_app/css/scrollbar.css' %}">
</head>

<body>
    <div class="countdown" id="countdown" data-value="{{ sledna_sesija.datum|date:'Y-m-d H:i:s' }}">
        <img id="staza-img" src="{% static sledna_trka.staza_slika %}">
        <h1 id="cntd"></h1>
        <h4>денови часови минути секунди</h4>
        <br>
        <div class="dropdown">
            <button class="dropbtn" id="dropButton">{{ sledna_sesija.ime|prevedi }}</button>
            <div class="dropdown-content">
                {% for sesija in sledna_trka.sesii.all|dictsort:"datum" %}
                    <h4 id="{{ sesija.session_id }}" onclick="smeniSesija('{{ sesija.session_id }}')" data-value="{{ sesija.datum|date:'Y-m-d H:i:s' }}">{{ sesija.ime|prevedi }}</h4>
                {% endfor %}
            </div>
        </div>
        <br>
        <h2 id="traka">{{ sledna_trka.drzava }} - {{ sledna_trka.staza }}</h2>
    </div>
    <a href="{% url 'formula_app:app-novosti' %}" class="strelka">
        <img src="https://popupfilmresidency.org/wp-content/uploads/2019/05/white-down-arrow-png-2.png">
    </a>

    <script src="{% static 'formula_app/js/countdown.js' %}"></script>

</body>

</html>

templates/formula_app/otvorena-vest.html
{% extends "base.html" %}
{% load static %}

{% block links %}
<link rel="stylesheet" type="text/css" href="{% static 'formula_app/css/novosti.css' %}">
<link rel="stylesheet" type="text/css" href="{% static 'formula_app/css/otvorena-vest.css' %}">
{% endblock links %}

{% block content %}
    <div class="container">
        <div class="otvorena-novost">
            <img src="{{ novost.slika }}">
    
            <h2>{{ novost.naslov }}</h2>
    
            <p>{{ novost.tekst }}</p>
        </div>
    
        <div class="stranicni-vesti">
            {% for vest in vesti %}
                <a class="karticka" href="{% url 'formula_app:app-otvorena-novost' novost_naslov=vest.naslov %}">
                    <div class="slika-container">
                        <img src="{{ vest.slika }}">
                    </div>
                    <h2>{{ vest.naslov }}</h2>
                    <p>{{ vest.privju }}</p>
                </a>
            {% endfor %}
        </div>
    </div>

{%  endblock content %}

templates/formula_app/plasman.html
{% extends "base.html" %}
{% load static %}
{% load formatter %}

{% block links %}
<link rel="stylesheet" type="text/css" href="{% static 'formula_app/css/plasman.css' %}">
{% endblock links %}

{% block content %}

<div class="plasman-container">

    <h2 id="vozaci">Возачи</h2>
    <div class="plasman-vozaci">

        {% for vozac in vozaci %}

        <div id="vozaci" class="p-vozac">
            <h2>{{ vozac.pozicija }}</h2>
            <div class="drugio-font vozac-ime-blok boja-{{ vozac.tim.ime|zameni_prazno_mesto }}" >
                <div>
                    {{ vozac.ime }} <b>{{ vozac.prezime }}</b>
                </div>
                <div class="text-boja-{{ vozac.tim.ime.split|join:'-' }}">{{ vozac.tim.ime }}</div>
                
                <img class="zname" src="https://www.countries-ofthe-world.com/flags-normal/flag-of-{{ vozac.drzava|zameni_procent_dvaese|zameni_prazno_mesto }}.png">
                
            </div>
            <div class="slika-vozac" style="
                                    background-color: var(--{{vozac.tim.ime.lower|zameni_prazno_mesto}}-color);
                                    background-image: url('{% static vozac.slika.lower %}');
                                    box-shadow: 0 4px 8px 0 rgba(0, 0, 0, 0.1), 0 6px 20px 0 rgba(0, 0, 0, 0.1);
                                    ">
                <span class="poeni"><b>{{ vozac.poeni }}</b> pts</span>
            </div>
        </div>

        {% endfor %}
    </div>
    <h2 id="timovi">Тимови</h2>
    <div class="plasman-vozaci">

        {% for tim in timovi %}

        <div class="p-vozac" style="overflow-y: hidden;">
            <h2>{{ tim.pozicija }}</h2>
            <div class="drugio-font vozac-ime-blok boja-{{ tim.ime|zameni_prazno_mesto }}" >
                <div class="text-boja-{{ tim.ime.split|join:'-' }}" style="margin-top: 13%; margin-bottom: 13%">{{ tim.ime }}</div>
            </div>
            <img class="tim-slika" src="https://www.formula1.com/content/dam/fom-website/teams/2022/{{tim.ime.lower|zameni_prazno_mesto}}.png" alt="{{tim.ime}}">
            <div class="slika-vozac">
                <span class="poeni"><b>{{ tim.poeni }}</b> pts</span>
            </div>
            </div>

        {% endfor %}
    </div>

</div>
{% endblock content %}

templates/formula_app/raspored.html
{% extends "base.html" %}
{% load static %}
{% load formatter %}

{% block links %}
<link rel="stylesheet" type="text/css" href="{% static 'formula_app/css/raspored.css' %}">
{% endblock links %}

{% block content %}
<div class="content">

    {% for trka in trki %}
        {% if trka.status == "Confirmed" or trka.status == "Complete" %}
        <a href="{% url 'formula_app:app-traka-info' traka_id=trka.race_id %}" class="trka" 
        style="background-image: url({% static trka.pozadina_slika %});">
        <img src="{% static trka.staza_slika %}">
            
            <div class="trka-info">
                <h1>{{ trka.ime }}</h1>
                <h3>{{ trka.pocetok }}</h3>
            </div>
        </a>
        {% endif %}

    {% endfor %}
    
</div>
{% endblock content %}

templates/formula_app/register.html
{% extends "base.html" %}
{% load static %}       

{% block links %}
	<link type="text/css" rel="stylesheet" href="{% static 'formula_app/bootstrap/css/materialize.min.css' %}"  media="screen,projection"/>
	<link type="text/css" rel="stylesheet" href="{% static 'formula_app/bootstrap/css/style.css' %}"  media="screen,projection"/>

	<script type="text/javascript" src="https://code.jquery.com/jquery-3.2.1.min.js"></script>
	<script type="text/javascript" src="{% static 'formula_app/bootstrap/js/materialize.min.js' %}"></script>
{% endblock links %}


{% block content %} 
<!--Register--> 
<div class="container">
	<h1>Register</h1>
	<form class="form-group" method="POST" >
		{% csrf_token %}
		<div class="row">
			<div class="input-field col s12">
				{{ form.username }}
				<label for="id_username" data-error="Username already taken">Username</label>
			</div>
		</div>
		<div class="row">
			<div class="input-field col s12">
				{{ form.password1 }}
				<label for="id_password">Password</label>
			</div>
		</div>
		<div class="row">
			<div class="input-field col s12">
				{{ form.password2 }}
				<label for="id_password2">Repeat Password</label>
			</div>
		</div>
		<div class="row">
			<div class="col s12">
			<div class="right">
				<button class="btn blue waves-effect waves-light pull-s12">Register</button>
			</div>
			</div>
		</div>
	</form>
	{% if request.GET.next %}
		<input type="hidden" name="next" value="{{ request.GET.next }}">
		<p class="text-center">If you already have an account, <a href="/login/?next={{ request.GET.next }}">login</a> instead.</p>
	{% else %}
		<p class="text-center">If you already have an account, <a href="/login">login</a> instead.</p>
	{% endif %}
</div>

{% endblock %}

templates/formula_app/traka-info.html
{% extends "base.html" %}
{% load static %}
{% load formatter %}

{% block links %}
<link rel="stylesheet" type="text/css" href="{% static 'formula_app/css/traka-info.css' %}">
{% endblock links %}

{% block content %}
<div class="content">
    <div class="line-info" id="line-info">
        <h1>Formula One {{ traka.ime }}</h1>
        <h2> {{traka.drzava }}</h2>
    </div>
    <h1><span>Тркачка патека:</span> {{ traka.staza }}</h1>
    <img class="staza" src="{% static traka.staza_slika %}">

    <div class="info-wrapper">
        <!-- <div class="tekst-info">Lorem ipsum dolor sit amet consectetur adipisicing elit. Quam quasi voluptatem quaerat
            vero dolorem totam. Numquam perferendis quaerat ea odio optio omnis corrupti, cupiditate est ut. Deleniti
            atque quod sed.</div> -->
        <div class="sesii-info">
            {% for sesija in traka.sesii.all|dictsort:"datum" %}
            <div class="sesija">
                <span>{{ sesija.ime|prevedi }} </span> <span>{{sesija.datum|date:'H:i' }} {{sesija.datum|date:'D'|prevedi }}</span>
            </div>
            {% endfor %}
        </div>

        <div class="gumi-wrapper">
            <h2>На располагање</h2>
            <div class="gumi">
                <img src="https://upload.wikimedia.org/wikipedia/commons/thumb/d/df/F1_tire_Pirelli_PZero_Red.svg/512px-F1_tire_Pirelli_PZero_Red.svg.png" alt="Red">
                <img src="https://upload.wikimedia.org/wikipedia/commons/thumb/4/4d/F1_tire_Pirelli_PZero_Yellow.svg/512px-F1_tire_Pirelli_PZero_Yellow.svg.png" alt="Yellow">
                <img src="https://upload.wikimedia.org/wikipedia/commons/thumb/d/d6/F1_tire_Pirelli_PZero_White.svg/512px-F1_tire_Pirelli_PZero_White.svg.png" alt="White">
                <img src="https://upload.wikimedia.org/wikipedia/commons/thumb/8/86/F1_tire_Pirelli_Cinturato_Green.svg/512px-F1_tire_Pirelli_PZero_Green.svg.png" alt="Green">
                <img src="https://upload.wikimedia.org/wikipedia/commons/thumb/6/63/F1_tire_Pirelli_Cinturato_Blue.svg/512px-F1_tire_Pirelli_PZero_Blue.svg.png" alt="Blue">
            </div>
        </div>
    </div>
</div>

<script>
  window.onload = function(){
    // When the user scrolls the page, execute myFunction
    window.onscroll = function() {myFunction()};
    
    // Get the header
    const lineInfo = document.getElementById("line-info");
    
    // Get the offset position of the navbar
    var sticky = lineInfo.offsetTop;
    
    // Add the sticky class to the lineInfo when you reach its scroll position. Remove "sticky" when you leave the scroll position
    function myFunction() {
      if (window.pageYOffset > sticky) {
        lineInfo.classList.add("sticky");
      } else {
        lineInfo.classList.remove("sticky");
      }
    }
    
}
</script>
{% endblock content %}

templates/formula_app/welcome.html
{% extends "base.html" %}
{% load static %}


{% block content %}
<h1>Authentication successful</h1>
<h2>Welcome</h2>
{% endblock content %}